//Name : ADVAIT GURUNATH CHAVAN, PRN : 4119008, SEM 6 T.E. ELECTRONICS, ESRTOS LAB, ELL603
//Interfacing of LED's/Switches
ORG 0000H
LOOP : CLR P2.1
	   ACALL DELAY
	   SETB P2.1
	   ACALL DELAY
	   JMP LOOP
DELAY : MOV R3,#0FFH
REP : MOV R2,#0FFH
HERE : DJNZ R2,HERE
       DJNZ R3,REP
	   RET
END