//NAME : ADVAIT GURUNATH CHAVAN, PRN : 4119008, SEM : 6, T.E. ELECTRONICS
//ESRTOS LAB, ELL603, EXP : 2- LCD INTERFACING WITH 8051
ORG 00H
AGAIN : MOV A,#38H
		ACALL CW
		ACALL DELAY
		MOV A,#0EH
		ACALL CW
		ACALL DELAY
		MOV A,#01H
		ACALL CW
		ACALL DELAY
		MOV A,#06H
		ACALL CW
		ACALL DELAY
		MOV DPTR,#MY_NAME_BYTE
D1 : CLR A
	 MOVC A, @A+DPTR
	 ACALL DATA_
	 INC DPTR
	 SJMP D1
DATA_ : MOV P1,A
	  SETB P2.0
	  CLR P2.1
	  SETB P2.2
	  ACALL DELAY
	  ACALL DELAY
	  ACALL DELAY
	  ACALL DELAY
	  CLR P2.2
	  RET
CW : MOV P1,A
	 CLR P2.0
	 CLR P2.1
	 SETB P2.2
	 ACALL DELAY
	 CLR P2.2
	 RET
DELAY : MOV R3,#50
HERE2 : MOV R4,#200
HERE : DJNZ R4,HERE
	   DJNZ R3,HERE2
	   RET
MY_NAME_BYTE : DB"ADVAIT CHAVAN",0
END
		