//Name : ADVAIT GURUNATH CHAVAN, PRN : 4119008, SEM 6 ,T.E. ELECTRONICS, ESRTOS, ELL603
//EXP_1(B) : LED_INTERFACING WITH SWITCH
ORG 0000H
SETB P1.0
SETB P1.1
LOOP : MOV A,P1
	   RRC A
	   JC KEY_K2
	   CLR P2.0
	   ACALL DELAY
	   SJMP LOOP
KEY_K2 : RRC A
		 JC LOOP
		 SETB P2.0
		 ACALL DELAY
		 SJMP LOOP
DELAY : MOV R3,#0FFH
REP : MOV R2,#0FFH
HERE : DJNZ R2,HERE
	   DJNZ R3,REP
	   RET
END